title: "Imagine+ Seminar Series"
description: "The seminar series of the Imagine+ Network"
baseurl: "/IP-Seminar" # leave blank unless deploying in subpath
url: "https://alex-krull.github.io"

theme: minima   # Jekyll's built-in theme (simple and clean)

collections:
  posts:
    output: true
