title: "Imagine+ Seminar Series"
description: "The seminar series of the Imagine+ Network"
baseurl: "/IP-Seminar" # leave blank unless deploying in subpath
url: "https://alex-krull.github.io"

# theme: minima   # Jekyll's built-in theme (simple and clean)
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one



collections:
  posts:
    output: true
